baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Science & Nature' # title come from here


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Physics'
pageRef = '/physics'
weight = 20

[[menus.main]]
name = 'Planets'
pageRef = '/planets/'
weight = 30
    
[[menus.main]]
name = 'Mars'
pageRef = '/planets/mars'
parent = 'Planets'
weight = 1

[[menus.main]]
name = 'Biology'
pageRef = '/Biology'
weight = 40

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 50


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

