baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Physics'
pageRef = '/physics'
weight = 20

[[menus.main]]
name = 'Planets'
pageRef = '/planets'
weight = 30

[[menus.main]]
name = 'Biology'
pageRef = '/planets'
weight = 40

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
